name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: true  # This ensures submodules are initialized

      # Set up JDK 17 for Android/Kotlin development
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with Gradle (including R8 minification)
      - name: Build with Gradle
        run: ./gradlew build --info --stacktrace  # Added flags for more detailed output

      # Optionally, you can separate the minification step if needed
      - name: Minify Release Build
        run: ./gradlew assembleRelease --info --stacktrace  # Use this if you want to isolate minification issues

      # Run tests
      - name: Run tests
        run: ./gradlew test
